# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6551aa07729db4b4c284d69115556f5a16d529cc5a706c3238234f3ad8d01a7efcb0a040dbc97662adda281f7a881090b657d21e2493ee44fdd9bc486ea011a6

test:
  secret_key_base: 338379793fe628f3663a5d4d1f97355d8e57d4397fabeb91490d0d0a6763c857a480d429a2b86cb12f9d59e4ebb73f8403d18e280aa927bba34da92d8d7202c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
